package armerror

import (
	"fmt"

	"github.com/Azure/aks-deployer/pkg/apierror"
	"github.com/Azure/go-autorest/autorest"
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/ginkgo/extensions/table"
	. "github.com/onsi/gomega"
	"github.com/onsi/gomega/types"
)

var _ = Describe("Test ParseRawError", func() {

	err1 := fmt.Errorf("failed to delete resource group: resources.GroupsClient#Delete: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code=\"ScopeLocked\" Message=\"The scope '/subscriptions/42b89d42-fe26-4c68-bd08-c0db2a39354c/resourcegroups/MC_task5cluster_rg_task5cluster_eastus' cannot perform delete operation because following scope(s) are locked: '/subscriptions/42b89d42-fe26-4c68-bd08-c0db2a39354c/resourceGroups/MC_task5cluster_rg_task5cluster_eastus/providers/Microsoft.Network/loadBalancers/kubernetes'. Please remove the lock and try again.\"")
	err1r := fmt.Errorf(`failed to delete resource group: resources.GroupsClient#Delete: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code=\"ScopeLocked\" Message=\"The scope '/subscriptions/42b89d42-fe26-4c68-bd08-c0db2a39354c/resourcegroups/MC_task5cluster_rg_task5cluster_eastus' cannot perform delete operation because following scope(s) are locked: '/subscriptions/42b89d42-fe26-4c68-bd08-c0db2a39354c/resourceGroups/MC_task5cluster_rg_task5cluster_eastus/providers/Microsoft.Network/loadBalancers/kubernetes'. Please remove the lock and try again.\"`)
	err2 := fmt.Errorf("failed to delete resource group: resources.GroupsClient#Delete: Failure sending request: StatusCode=409 -- Original Error: Long running operation terminated with status 'Failed': Code=\"ResourceGroupDeletionTimeout\" Message=\"Deletion of resource group 'MC_dani-k8-cluster-group_dani-k8-cluster_westeurope' did not finish within the allowed time as resources with identifiers 'Microsoft.Compute/snapshots/snapshot_aff0c263-bfa0-4efa-8e99-d1a5aa4eae81' could not be deleted. The provisioning state of the resource group will be rolled back. The tracking Id is 'fb56d4d4-bd94-4100-a628-f1435372b85f'. Please check audit logs for more details.\"")
	err2r := fmt.Errorf(`failed to delete resource group: resources.GroupsClient#Delete: Failure sending request: StatusCode=409 -- Original Error: Long running operation terminated with status 'Failed': Code=\"ResourceGroupDeletionTimeout\" Message=\"Deletion of resource group 'MC_dani-k8-cluster-group_dani-k8-cluster_westeurope' did not finish within the allowed time as resources with identifiers 'Microsoft.Compute/snapshots/snapshot_aff0c263-bfa0-4efa-8e99-d1a5aa4eae81' could not be deleted. The provisioning state of the resource group will be rolled back. The tracking Id is 'fb56d4d4-bd94-4100-a628-f1435372b85f'. Please check audit logs for more details.\"`)
	err3 := fmt.Errorf("failed to delete resource group: resources.GroupsClient#Delete: Failure sending request: StatusCode=0 -- Original Error: Get https://management.azure.com/subscriptions/c1089427-83d3-4286-9f35-5af546a6eb67/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1NQzo1RkJCVVJOUzoyREFLUzoyREdBOjJEVEVTVDoyRENSRUFURToyRDM2MTE6Mnw2OTQ3OTYzRkRCMDk2MEJFLUVBU1RVUyIsImpvYkxvY2F0aW9uIjoiZWFzdHVzIn0?api-version=2016-09-01: dial tcp: lookup management.azure.com on 10.0.0.10:53: dial udp 10.0.0.10:53: i/o timeout")
	err4 := autorest.NewErrorWithError(fmt.Errorf(`failed request: autorest/azure: Service returned an error. Status=<nil> Code="ResourceGroupDeletionTimeout" Message="Deletion of resource group 'MC_ClusterResources_MapCluster_eastus' did not finish within the allowed time as resources with identifiers 'Microsoft.Network/networkSecurityGroups/aks-agentpool-30814457-nsg,Microsoft.Network/routeTables/aks-agentpool-30814457-routetable,Microsoft.Network/virtualNetworks/aks-vnet-30814457' could not be deleted. The provisioning state of the resource group will be rolled back. The tracking Id is '56e8832d-1f24-43f0-9e2c-bf68743366b1'. Please check audit logs for more details." Details=[{"Code":null,"Details":null,"Innererror":null,"Message":"{\"error\":{\"code\":\"InUseNetworkSecurityGroupCannotBeDeleted\",\"message\":\"Network security group /subscriptions/fad79396-0443-4fec-bb05-2d89298c67e3/resourceGroups/MC_ClusterResources_MapCluster_eastus/providers/Microsoft.Network/networkSecurityGroups/aks-agentpool-30814457-nsg cannot be deleted because it is in use by the following resources: /subscriptions/fad79396-0443-4fec-bb05-2d89298c67e3/resourceGroups/MC_ClusterResources_MapCluster_eastus/providers/Microsoft.Network/virtualNetworks/aks-vnet-30814457/subnets/aks-subnet.\",\"details\":[]}}","Target":"/subscriptions/fad79396-0443-4fec-bb05-2d89298c67e3/resourceGroups/MC_ClusterResources_MapCluster_eastus/providers/Microsoft.Network/networkSecurityGroups/aks-agentpool-30814457-nsg"},{"Code":null,"Details":null,"Innererror":null,"Message":"{\"error\":{\"code\":\"InUseRouteTableCannotBeDeleted\",\"message\":\"Route table aks-agentpool-30814457-routetable is in use and cannot be deleted.\",\"details\":[]}}","Target":"/subscriptions/fad79396-0443-4fec-bb05-2d89298c67e3/resourceGroups/MC_ClusterResources_MapCluster_eastus/providers/Microsoft.Network/routeTables/aks-agentpool-30814457-routetable"},{"Code":null,"Details":null,"Innererror":null,"Message":"{\"error\":{\"code\":\"InUseSubnetCannotBeDeleted\",\"message\":\"Subnet aks-subnet is in use by /subscriptions/fad79396-0443-4fec-bb05-2d89298c67e3/resourceGroups/MAPVMs/providers/Microsoft.Network/networkInterfaces/urlgenerator41/ipConfigurations/ipconfig1 and cannot be deleted.\",\"details\":[]}}","Target":"/subscriptions/fad79396-0443-4fec-bb05-2d89298c67e3/resourceGroups/MC_ClusterResources_MapCluster_eastus/providers/Microsoft.Network/virtualNetworks/aks-vnet-30814457"}]`),
		"resources.GroupsClient",
		"Delete",
		nil,
		"Failure sending request")
	err5 := fmt.Errorf("resources.GroupsClient#CreateOrUpdate: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code=\"AuthorizationFailed\" Message=\"The client '6f3f080f-fae8-41ce-b1c5-91e9044e1be7' with object id '6f3f080f-fae8-41ce-b1c5-91e9044e1be7' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourcegroups/write' over scope '/subscriptions/3fb785a4-b078-474e-835c-c7168c5dfa98/resourcegroups/MC_20533E0703-LabRG_20533E0703-k8scluster_westeurope'.\"")
	err6 := fmt.Errorf("resources.GroupsClient#CreateOrUpdate: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code=\"RequestDisallowedByPolicy\" Message=\"Resource 'MC_sslng-PaaS-prd-rgp-001_sslng_westeurope' was disallowed by policy. Policy identifiers: ......\"")
	err7 := fmt.Errorf("Deleting the customer provisioned DNS Zone failed. Detail: dns.RecordSetsClient#Delete: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\"BadRequest\" Message=\"The domain name 'be46a36e78594904bf4b.east us.int.aksapp.io' is invalid. The provided record set relative name 'be46a36e78594904bf4b.east us' is invalid.\"")
	err8 := autorest.NewErrorWithError(nil, "resources.GroupsClient", "Delete", nil, "Failure sending request")
	err9 := fmt.Errorf("autorest/azure: Service returned an error. Status=403 Code=\"RequestDisallowedByPolicy\" Message=\"Resource 'MC_slaxAKS-CLUSTER1-AKS_slax-aks-cluster1-sg_southeastasia' was disallowed by policy. Policy identifiers: '[{\"policyAssignment\":{\"name\":\"policy-pru1-dev-enforcersgtags\",\"id\":\"/subscriptions/d2841aaa-729d-4efc-85ee-baca10ac44be/providers/Microsoft.Authorization/policyAssignments/pas-pru1-dev-enforcersgtags\"},\"policyDefinition\":{\"name\":\"Enforce resource group tags\",\"id\":\"/subscriptions/d2841aaa-729d-4efc-85ee-baca10ac44be/providers/Microsoft.Authorization/policyDefinitions/pol-pru1-dev-enforcersgtags\"}}]'.\" Target=\"MC_slaxAKS-CLUSTER1-AKS_slax-aks-cluster1-sg_southeastasia\" AdditionalInfo=[{\"info\":{\"evaluationDetails\":{\"evaluatedExpressions\":[{\"expression\":\"type\",\"expressionValue\":\"Microsoft.Resources/subscriptions/resourcegroups\",\"operator\":\"Equals\",\"path\":\"type\",\"result\":\"True\",\"targetValue\":\"Microsoft.Resources/subscriptions/resourceGroups\"},{\"expression\":\"tags['BusinessUnit']\",\"operator\":\"Exists\",\"path\":\"tags['BusinessUnit']\",\"result\":\"True\",\"targetValue\":\"false\"},{\"expression\":\"tags['Environment']\",\"operator\":\"Exists\",\"path\":\"tags['Environment']\",\"result\":\"True\",\"targetValue\":\"false\"},{\"expression\":\"tags['Location']\",\"operator\":\"Exists\",\"path\":\"tags['Location']\",\"result\":\"True\",\"targetValue\":\"false\"},{\"expression\":\"tags['ApplicationName']\",\"operator\":\"Exists\",\"path\":\"tags['ApplicationName']\",\"result\":\"True\",\"targetValue\":\"false\"},{\"expression\":\"tags['ApplicationOwner']\",\"operator\":\"Exists\",\"path\":\"tags['ApplicationOwner']\",\"result\":\"True\",\"targetValue\":\"false\"}]},\"policyAssignmentDisplayName\":\"policy-pru1-dev-enforcersgtags\",\"policyAssignmentId\":\"/subscriptions/d2841aaa-729d-4efc-85ee-baca10ac44be/providers/Microsoft.Authorization/policyAssignments/pas-pru1-dev-enforcersgtags\",\"policyAssignmentName\":\"pas-pru1-dev-enforcersgtags\",\"policyAssignmentScope\":\"/subscriptions/d2841aaa-729d-4efc-85ee-baca10ac44be\",\"policyDefinitionDisplayName\":\"Enforce resource group tags\",\"policyDefinitionEffect\":\"deny\",\"policyDefinitionId\":\"/subscriptions/d2841aaa-729d-4efc-85ee-baca10ac44be/providers/Microsoft.Authorization/policyDefinitions/pol-pru1-dev-enforcersgtags\",\"policyDefinitionName\":\"pol-pru1-dev-enforcersgtags\"},\"type\":\"PolicyViolation\"}]")
	err10 := fmt.Errorf("autorest/azure: Service returned an error. Status=409 Code=\"ResourceGroupQuotaExceeded\" Message=\"Creating the resource group 'MC_aksrnr-fafb0636_cluster_eastus2euap' would exceed the quota of '980'. The current resource group count is '980', please delete some groups before creating a new one.\"")
	err11 := fmt.Errorf("Code=\"DeploymentFailed\" Message=\"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.\" Details=[{\"code\":\"BadRequest\",\"message\":\"{\r\n  \"error\": {\r\n    \"details\": [],\r\n    \"code\": \"SubnetIsFull\",\r\n    \"message\": \"Subnet default-subnet with address prefix 10.0.0.0/24 is already full.\"\r\n  }\r\n}\"}]")
	err12 := fmt.Errorf("Code=\"DeploymentFailed\" Message=\"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.\" Details=[{\"code\":\"BadRequest\",\"message\":\"{\r\n  \"error\": {\r\n    \"code\": \"ResourceNotPermittedOnDelegatedSubnet\",\r\n    \"message\": \"Resource /subscriptions/0c8875c7-e423-4caa-827a-1f0350bd8dd3/resourceGroups/MC_JackieR_TestNetwork_westus/providers/Microsoft.Network/networkInterfaces/aks-agentpool-14174824-nic-1/ipConfigurations/ipconfig1 cannot be created in or updated to use the subnet /subscriptions/0c8875c7-e423-4caa-827a-1f0350bd8dd3/resourceGroups/JackieR/providers/Microsoft.Network/virtualNetworks/JackieR-vnet/subnets/default since it has delegation(s) [Microsoft.ContainerInstance/containerGroups: /subscriptions/0c8875c7-e423-4caa-827a-1f0350bd8dd3/resourceGroups/JackieR/providers/Microsoft.Network/virtualNetworks/JackieR-vnet/subnets/default/delegations/aciDelegation] to external services.\",\r\n    \"details\": []\r\n  }\r\n}\"},")
	err13 := fmt.Errorf("autorest/azure: Service returned an error. Status=409 Code=\"ScopeLocked\" Message=\"The scope '/subscriptions/8ecadfc9-d1a3-4ea4-b844-0d9f87e4d7c8/resourceGroups/adilli-rg/providers/Microsoft.Compute/virtualMachineScaleSets/adilliVmss' cannot perform delete operation because following scope(s) are locked: '/subscriptions/8ecadfc9-d1a3-4ea4-b844-0d9f87e4d7c8/resourceGroups/adilli-rg'. Please remove the lock and try again.\"")
	err14 := fmt.Errorf("autorest/azure: Service returned an error. Status=429 Code=\"TooManyRequests\" Message=\"The server rejected the request because too many requests have been received for this subscription.\" Details=[{\"code\":\"TooManyRequests\",\"message\":\"{\"operationGroup\":\"HighCostGetVMScaleSet30Min\",\"startTime\":\"2019-10-28T20:44:19.5083103+00:00\",\"endTime\":\"2019-10-28T20:59:19.5083103+00:00\",\"allowedRequestCount\":1441,\"measuredRequestCount\":1563}\",\"target\":\"HighCostGetVMScaleSet30Min\"}] InnerError={\"internalErrorCode\":\"TooManyRequestsReceived\"}}")
	err15 := fmt.Errorf("VMSSAgentPoolReconciler retry failed: deployment operations failed with error messages: {\"code\": \"VMExtensionProvisioningError\",\"message\": \"VM has reported a failure when processing extension 'vmssCSE'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=50\n[stdout]\nThu Oct 31 05:53:51 UTC 2019,aks-default-92520957-vmss000000\n\n[stderr]\n\".\",}")
	err16 := fmt.Errorf("VMSSAgentPoolReconciler retry failed: deployment operations failed with error messages: {\"code\": \"VMExtensionProvisioningError\",\"message\": \"VM has reported a failure when processing extension 'vmssCSE'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=84\n[stdout]\nThu Oct 31 05:53:51 UTC 2019,aks-default-92520957-vmss000000\n\n[stderr]\n\".\",}")
	err17 := fmt.Errorf("VMSSAgentPoolReconciler retry failed: deployment operations failed with error messages: {\r\n  \"code\": \"PublicIPCountLimitExceededByVMScaleSet\",\r\n  \"message\": \"The requested number of publicIPAddresses 2 for VM Scale Set /subscriptions/aedc2c99-9471-47a7-9792-0a2392c269cf/resourceGroups/MC_NSM-CI_AZURE-4-2020-3-16-121654-86F7DB0B58_CENTRALUS/providers/Microsoft.Compute/virtualMachineScaleSets/aks-nodepool1-65165126-vmss will exceed the maximum number of publicIPAddresses allowed 20 for subscription aedc2c99-9471-47a7-9792-0a2392c269cf.\"\r\n } ")
	err18 := fmt.Errorf("VMSSAgentPoolReconciler retry failed: deployment operations failed with error messages: {\"code\": \"VMExtensionProvisioningError\",\"message\": \"VM has reported a failure when processing extension 'vmssCSE'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=51\n[stdout]\nThu Oct 31 05:53:51 UTC 2019,aks-default-92520957-vmss000000\n\n[stderr]\n\".\",}")
	err19 := fmt.Errorf("VMSSAgentPoolReconciler retry failed: deployment operations failed with error messages: {\"code\": \"OverconstrainedZonalAllocationRequest\",\"messsage\": \"Allocation failed. VM(s) with the following constraints cannot be allocated, because the condition is too restrictive. Please remove some constraints and try again. Constraints applied are:\n - Availability Zone\n - VM Size\n}")
	err20 := fmt.Errorf("Create agent pool 'agentpool' failed with error deployment operations failed with error messages: {\"code\": \"GatewaySubnet\",\"message\": \"Subnet with name 'GatewaySubnet' can be used only for the Gateway resource.\"}")
	err21 := fmt.Errorf("Code=\"InvalidTemplateDeployment\" Message=\"The template deployment 'c6a42716-c046-4ef0-ade8-dd82c3e37000-b22d8bac' is not valid according to the validation procedure. The tracking id is 'adc966f5-4e3d-43a6-8926-75abf2d05155'. See inner errors for details.\" Details=[{\"code\":\"QuotaExceeded\",\"message\":\"Operation could not be completed as it results in exceeding approved Total Regional Cores quota. Additional details - Deployment Model: Resource Manager, Location: australiaeast, Current Limit: 20, Current Usage: 20, Additional Required: 6, (Minimum) New Limit Required: 26. Submit a request for Quota increase at https://aka.ms/ProdportalCRP/?#create/Microsoft.Support/Parameters/{\"subId\":\"c79c9427-b0eb-4c8d-955a-88d03978dbd1\",\"pesId\":\"06bfd9d3-516b-d5c6-5802-169c800dec89\",\"supportTopicId\":\"e12e3d1d-7fa0-af33-c6d0-3c50df9658a3\"} by specifying parameters listed in the ‘Details’ section for deployment to succeed. Please read more about quota limits at https://docs.microsoft.com/en-us/azure/azure-supportability/regional-quota-requests.\"}]")
	err22 := fmt.Errorf("autorest/azure: Service returned an error. Status=409 Code=\"Conflict\" Message=\" Run command extension execution is in progress. Please wait for completion before invoking a run command")
	err23 := fmt.Errorf("Code=\"ReservedResourceName\" Message=\"The resource name 'aks-pi-windows-agentpool' or a part of the name is a trademarked or reserved word.\"")
	err24 := fmt.Errorf("reconcile vmss agent pools '[0]' error: VMSSAgentPoolReconciler retry failed: {\"code\": \"NodesNotReady\", \"message\": \"Not all nodes reached Ready state. Expected: 1, Actual: 0\"}")
	err25 := fmt.Errorf("standardLoadBalancerReconciler retry failed: Code=\"StandardSkuPublicIPCountLimitReached\" Message=\"Cannot create more than 10 standard sku publicIpAddresses for this subscription in this region.\" Details=[]")
	err26 := fmt.Errorf("deploy template without agent pool error: Code=\"InvalidTemplateDeployment\" Message=\"The template deployment failed because of policy violation. Please see details for more information.\"")
	err27 := fmt.Errorf("VMSSAgentPoolReconciler retry failed: Code=\"SpecifiedAllocatedOutboundPortsForOutboundRuleExceedsTotalNumberOfAvailablePorts\" Message=\"Specified Allocated Outbound Ports 1600 for Outbound Rule /subscriptions/28294233-9358-4c2b-8e72-c62ba493f792/resourceGroups/mc_vienna-eastus2euap-01_vienna-eastus2euap-01_eastus2euap/providers/Microsoft.Network/loadBalancers/kubernetes/outboundRules/aksOutboundRule exceeds total number of available ports 1576. Reduce allocated ports or increase number of IP addresses for outbound rule.\"")
	err28 := fmt.Errorf("VMSSAgentPoolReconciler retry failed: VMSS 'vmsstest' reported failure details='{instance 0 has extension error details : {vmssCSE error messages : {vmssCSE exit status=50, output=Thu Oct 31 05:53:51 UTC 2019,aks-default-92520957-vmss000000, error=;};instance 1 has extension error details : {vmssCSE exit status=84, output=Thu Oct 31 05:53:51 UTC 2019,aks-default-92520957-vmss000001, error=;}}")
	err29 := fmt.Errorf("VMSSAgentPoolReconciler retry failed: VMSS 'vmsstest' reported failure details={instance 1 has no instance views available, vmssInstanceErrorCode=NoVMSSInstanceView;}")
	err30 := fmt.Errorf("VMSSAgentPoolReconciler retry failed: VMSS 'vmsstest' reported failure details={VMSS test instance 1 has no instance views available, vmssInstanceErrorCode=NoVMSSInstanceView;VMSS test instance 2 vmssCSE error messages : {vmssCSE exit status=50, output=Thu Oct 31 05:53:51 UTC 2019,aks-default-92520957-vmss000000};}")
	err31 := fmt.Errorf("autorest/azure: Service returned an error. Status=429 Code=\"SubscriptionRequestsThrottled\" Message=\"The client '' with object id '' does not have authorization to perform action 'Microsoft.Authorization/roleAssignments/write' over scope '/subscriptions//providers/Microsoft.Authorization/roleAssignments/' or the scope is invalid. If access was recently granted, please refresh your credentials.\"")
	err32 := fmt.Errorf("autorest/azure: Service returned an error. Status=429 Code=\"Throttled\" Message=\"Too many operations are requested. Current operation is throttled.\"")
	err33 := fmt.Errorf("autorest/azure: Service returned an error. Status=400 Code=\"RoleAssignmentLimitExceeded\" Message=\"No more role assignments can be created.\"")
	apierror := apierror.NewError(apierror.ClientError, apierror.PodDrainFailure, "oops", "", "")
	doublewrappedapierror := fmt.Errorf("double wrapping %w", fmt.Errorf("wrapping %w", apierror))

	DescribeTable("Test ParseRawError",
		func(err error, expectedCategory string, expectedCode string, expectedReturnedError interface{}) {
			/*
				Including this check for expectedCode != "" because in some of the test cases before, they didn't care about the actualCode. See example below
				err8 := autorest.NewErrorWithError(nil, "resources.GroupsClient", "Delete", nil, "Failure sending request")
				cat8, _, rt8 := ParseRawError(err8)
				Expect(string(cat8)).To(Equal("InternalError"))
				Expect(rt8).To(Equal(err8.Error()))

				If it wasn't cared about in the test cases before, then we shouldn't care about them in the new table-driven way
			*/
			if expectedCode != "" {
				actualCategory, actualCode, actualReturnedError := ParseRawError(err)
				Expect(string(actualCategory)).To(Equal(expectedCategory))
				Expect(string(actualCode)).To(Equal(expectedCode))
				Expect(string(actualReturnedError)).To(Equal(expectedReturnedError))

			} else {
				actualCategory, _, actualReturnedError := ParseRawError(err)
				Expect(string(actualCategory)).To(Equal(expectedCategory))
				Expect(string(actualReturnedError)).To(Equal(expectedReturnedError))
			}
		},
		Entry("Test SpecifiedAllocatedOutboundPortsForOutboundRuleExceedsTotalNumberOfAvailablePorts==ClientError", err27, "ClientError", "SpecifiedAllocatedOutboundPortsForOutboundRuleExceedsTotalNumberOfAvailablePorts", err27.Error()),
		Entry("Test ScopeLocked==ClientError", err1, "ClientError", "ScopeLocked", err1.Error()),
		Entry("Test ScopeLocked==ClientError2", err1r, "ClientError", "ScopeLocked", err1r.Error()),
		Entry("Test ResourceGroupDeletionTimeout==ClientError", err2, "ClientError", "ResourceGroupDeletionTimeout", err2.Error()),
		Entry("Test ResourceGroupDeletionTimeout==ClientError2", err2r, "ClientError", "ResourceGroupDeletionTimeout", err2r.Error()),
		Entry("Test InternalOperationError==InternalError", err3, "InternalError", "InternalOperationError", err3.Error()),
		Entry("Test InUseNetworkSecurityGroupCannotBeDeleted==ClientError", err4, "ClientError", "", err4.Original.Error()),
		Entry("Test AuthorizationFailed==ClientError", err5, "ClientError", "AuthorizationFailed", err5.Error()),
		Entry("Test RequestDisallowedByPolicy==ClientError", err6, "ClientError", "RequestDisallowedByPolicy", err6.Error()),
		Entry("Test BadRequest==ClientError", err7, "ClientError", "BadRequest", err7.Error()),
		Entry("Test Unknown==InternalError", err8, "InternalError", "", err8.Error()),
		Entry("Test RequestDisallowedByPolicy==ClientError", err9, "ClientError", "RequestDisallowedByPolicy", err9.Error()),
		Entry("Test ResourceGroupQuotaExceeded==ClientError", err10, "ClientError", "", err10.Error()),
		Entry("Test BadRequest==ClientError", err11, "ClientError", "", err11.Error()),
		Entry("Test BadRequest==ClientError", err12, "ClientError", "", err12.Error()),
		Entry("Test ScopeLocked==ClientError", err13, "ClientError", "ScopeLocked", err13.Error()),
		Entry("Test TooManyRequests==ClientError", err14, "ClientError", "TooManyRequests", err14.Error()),
		Entry("Test OutboundConnFailVMExtensionError==ClientError", err15, "ClientError", "OutboundConnFailVMExtensionError", err15.Error()),
		Entry("Test GpuDriversStartFailVMExtensionError==InternalError", err16, "InternalError", "GpuDriversStartFailVMExtensionError", err16.Error()),
		Entry("Test PublicIPCountLimitExceededByVMScaleSet==ClientError", err17, "ClientError", "PublicIPCountLimitExceededByVMScaleSet", err17.Error()),
		Entry("Test K8SAPIServerConnFailVMExtensionError==ClientError", err18, "ClientError", "K8SAPIServerConnFailVMExtensionError", err18.Error()),
		Entry("Test OverconstrainedZonalAllocationRequest==ClientError", err19, "ClientError", "OverconstrainedZonalAllocationRequest", err19.Error()),
		Entry("Test GatewaySubnet==ClientError", err20, "ClientError", "GatewaySubnet", err20.Error()),
		Entry("Test QuotaExceeded==ClientError", err21, "ClientError", "QuotaExceeded", err21.Error()),
		Entry("Test Conflict==InternalError", err22, "InternalError", "Conflict", err22.Error()),
		Entry("Test ReservedResourceName==ClientError", err23, "ClientError", "ReservedResourceName", err23.Error()),
		Entry("Test NodesNotReady==InternalError", err24, "InternalError", "NodesNotReady", err24.Error()),
		Entry("Test StandardSkuPublicIPCountLimitReached==ClientError", err25, "ClientError", "StandardSkuPublicIPCountLimitReached", err25.Error()),
		Entry("Test PolicyViolation==ClientError", err26, "ClientError", "PolicyViolation", err26.Error()),
		Entry("Test apierror pass through", apierror, "ClientError", "PodDrainFailure", apierror.Message),
		Entry("Test double wrapped apierror pass through", doublewrappedapierror, "ClientError", "PodDrainFailure", apierror.Message),
		Entry("Test exit status 50 is client error", err28, "ClientError", "OutboundConnFailVMExtensionError", err28.Error()),
		Entry("Test vmssInstanceErrorCode is internal error", err29, "InternalError", "NoVMSSInstanceView", err29.Error()),
		Entry("Test ParseRawError will return the first vmssInstanceErrorCode as internal error", err30, "InternalError", "NoVMSSInstanceView", err30.Error()),
		Entry("Test SubscriptionRequestsThrottled==ClientError", err31, "ClientError", "", err31.Error()),
		Entry("Test Throttled==ClientError", err32, "ClientError", "", err32.Error()),
		Entry("Test RoleAssignmentLimitExceeded isclient error", err33, "ClientError", "RoleAssignmentLimitExceeded", err33.Error()),
	)
})

var _ = Describe("Test IsErrorStringVMExtensionError", func() {

	err1 := fmt.Errorf(`failed to delete resource group: resources.GroupsClient#Delete: Failure sending request: StatusCode=0 -- Original Error: Get https://management.azure.com/subscriptions/c1089427-83d3-4286-9f35-5af546a6eb67/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1NQzo1RkJCVVJOUzoyREFLUzoyREdBOjJEVEVTVDoyRENSRUFURToyRDM2MTE6Mnw2OTQ3OTYzRkRCMDk2MEJFLUVBU1RVUyIsImpvYkxvY2F0aW9uIjoiZWFzdHVzIn0?api-version=2016-09-01: dial tcp: lookup management.azure.com on 10.0.0.10:53: dial udp 10.0.0.10:53: i/o timeout`)
	err2 := fmt.Errorf("VMSSAgentPoolReconciler retry failed: deployment operations failed with error messages: {\"code\": \"VMExtensionProvisioningError\",\"message\": \"VM has reported a failure when processing extension 'vmssCSE'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=50\n[stdout]\nThu Oct 31 05:53:51 UTC 2019,aks-default-92520957-vmss000000\n\n[stderr]\n\".\",}")
	err3 := fmt.Errorf("VMSSAgentPoolReconciler retry failed: deployment operations failed with error messages: {\"code\": \"VMExtensionProvisioningError\",\"message\": \"VM has reported a failure when processing extension 'vmssCSE'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=84\n[stdout]\nThu Oct 31 05:53:51 UTC 2019,aks-default-92520957-vmss000000\n\n[stderr]\n\".\",}")
	err4 := fmt.Errorf("VMSSAgentPoolReconciler retry failed: VMSSAgentPoolReconciler retry failed: VMSS 'vmsstest' reported failure details={instance 0 has extension error details : {vmssCSE error messages : {vmssCSE exit status=50, output=Thu Oct 31 05:53:51 UTC 2019,aks-default-92520957-vmss000000, error=;};instance 1 has extension error details : {vmssCSE exit status=84, output=Thu Oct 31 05:53:51 UTC 2019,aks-default-92520957-vmss000001, error=;}}")
	DescribeTable("Test IsErrorStringVMExtensionError", func(err error, expectedCode string, expectedOk types.GomegaMatcher) {
		actualCode, actualOk := IsErrorStringVMExtensionError(err.Error())
		Expect(actualOk).To(expectedOk)
		Expect(actualCode).To(Equal(expectedCode))
	},
		Entry("Test No exit status is not VMExtensionError", err1, "", BeFalse()),
		Entry("Test status=50 is OutboundConnFailVMExtensionError", err2, "OutboundConnFailVMExtensionError", BeTrue()),
		Entry("Test status=84 is GpuDriversStartFailVMExtensionError", err3, "GpuDriversStartFailVMExtensionError", BeTrue()),
		Entry("Test status=50 is OutboundConnFailVMExtensionError", err4, "OutboundConnFailVMExtensionError", BeTrue()))
})
